### ISSUE TITLE
登录失败!

### ISSUE THREAD

**Issue by AndyFree96** [baiwumm/vue2-admin#3]
已⭐，感谢作者的开源贡献👏👏👏

# 环境

- 操作系统: Windows 11 专业版本 22621.3007
- Nodejs版本: 16.16.0
- Yarn: 1.22.21
- npm: 8.11.0

# 情况复现

将项目`clone`到本地后，分别按照**Xmw_server**和**Xmw_web**项目的README文件安装相关的包。新建`vue2_baiwumm_com`数据库(Xmw_server项目中的`config.default.js`可见)，并将[作者博客](https://baiwumm.com/)提供的SQL文件将数据库数据导入。之后执行`yarn run debug`命令启动后端项目，修改前端项目的API请求地址为本地刚启动的后端地址，再执行`yarn serve`启动前端项目。

如下图所示，可以正常地从本地获取验证码：

![image](https://github.com/baiwumm/Vue2-Admin/assets/41809797/e408be5b-c92b-45dd-9630-04bdc1cd658a)

输入用户名`admin`和 密码`123456`后，前端页面显示如下:

![image](https://github.com/baiwumm/Vue2-Admin/assets/41809797/3838fabf-2e4d-4026-9b4a-ce0d27941d7e)

终端显示如下:

![image](https://github.com/baiwumm/Vue2-Admin/assets/41809797/cdc72b66-2270-47c6-bf3f-9438cd54b599)

# 尝试方案

通过调试发现**Xmw_server**项目的`home.js`文件定义的`generateVerifCode`方法:

```javascript
  async generateVerifCode() {
      ......
      ctx.session.verifCode = captcha.text.toLowerCase(); // 存session用于验证接口获取文字码
      ......
}
```

将验证码保存到`ctx.session.verifCode`中，然后在同文件的`login`方法中，获取`ctx.session.verifCode`时的值为`undefined`。

```javascript
 async login() {
  ......
  if (ctx.session.verifCode.toLowerCase() !== verifyCode.toLowerCase()) {
          return (ctx.body = { state: 0, msg: "验证码错误!" });
        }
 ......
}
```

导致出现`login方法报错：TypeError: Cannot read properties of undefined (reading 'toLowerCase')`错误。

我的解决方案是，在`home.js`顶部增加了一个全局的`let globalScopeVerifCode = ""`变量，然后在`generateVerifCode`方法中增加一条赋值语句`globalScopeVerifCode = captcha.text.toLowerCase();`，最后将`login`方法的中的代码段:

```javascript
 if (ctx.session.verifCode.toLowerCase() !== verifyCode.toLowerCase()) {
          return (ctx.body = { state: 0, msg: "验证码错误!" });
        }
```

改为:

```javascript
 if (globalScopeVerifCode .toLowerCase() !== verifyCode.toLowerCase()) {
          return (ctx.body = { state: 0, msg: "验证码错误!" });
        }
```

可正常登录并进入系统中。

# 问题

请问作者有遇到这个问题吗？如何解决的呢？

期待回复😊😊😊

**Comment by baiwumm** [comment]
![image](https://github.com/baiwumm/Vue2-Admin/assets/40554571/0f05f915-9556-4e66-a14c-3aa6d1ead935)
这好像是 egg.js 早期版本的问题，不知道现在解决了没有，你可以百度查一下，好像改这两个配置就可以，你试试

**Comment by AndyFree96** [comment]
> ![image](https://private-user-images.githubusercontent.com/40554571/296441224-0f05f915-9556-4e66-a14c-3aa6d1ead935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNzcxNzgsIm5iZiI6MTcwNTI3Njg3OCwicGF0aCI6Ii80MDU1NDU3MS8yOTY0NDEyMjQtMGYwNWY5MTUtOTU1Ni00ZTY2LWExNGMtM2FhNmQxZWFkOTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAwMDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyN2I5NDIxZWFjNjYzNGYyNjA4N2ZmNDhjNTExZTc2YzAzNmYzZTc3YTU4MTA5ZjI2MGIwOTZiMmNlMTVhYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5uCt7jafMaPAsuLBifUGiNrmGhPEcHxxei4LUpIXiuQ) 这好像是 egg.js 早期版本的问题，不知道现在解决了没有，你可以百度查一下，好像改这两个配置就可以，你试试

感谢回复，已尝试你提供的思路，修改`dominWhiteList`和`origin`之后，Chrome浏览器的`Network`选项卡内容如下：

![image](https://github.com/baiwumm/Vue2-Admin/assets/41809797/465d3437-a2b4-4676-b1e3-627146e23724)

## 补充

在`macOS 14.1.1`操作系统上用`Node.js 16.16.0`运行项目表现正常。

## 问题复现

参考 https://github.com/eggjs/egg)](https://github.com/eggjs/egg 新建项目，将`home.js`、`router.js`和`config.default.js`分别修改为如下内容：

**home.js**
```javascript
const { Controller } = require("egg");

class HomeController extends Controller {
  async index() {
    const { ctx } = this;
    ctx.session.index = "index";
    ctx.body = "hi, egg";
  }

  async pointA() {
    const { ctx } = this;
    ctx.body = ctx.session.index;
    console.log("pointA Session", ctx.session.index);
  }

  async pointB() {
    const { ctx } = this;
    ctx.session.pointB = "pointB";
    ctx.body = ctx.session.index;
    console.log("pointB Session", ctx.session.index);
  }

  async pointC() {
    const { ctx } = this;
    ctx.body = `${ctx.session.index} ${ctx.session.pointB}`;
    console.log("pointC Session", ctx.session.index, ctx.session.pointB);
  }
}

module.exports = HomeController;

```

**router.js**
```javascript
/**
 * @param {Egg.Application} app - egg application
 */
module.exports = (app) => {
  const { router, controller } = app;
  router.get("/", controller.home.index);
  router.get("/pointA", controller.home.pointA);
  router.post("/pointB", controller.home.pointB);
  router.post("/pointC", controller.home.pointC);
};
```

**config.default.js**
```javascript
/**
 * @param {Egg.Application} app - egg application
 */
module.exports = (app) => {
  const { router, controller } = app;
  router.get("/", controller.home.index);
  router.get("/pointA", controller.home.pointA);
  router.post("/pointB", controller.home.pointB);
  router.post("/pointC", controller.home.pointC);
};
```

### 访问主页

浏览器访问`http://127.0.0.1:7001`可看到：

![image](https://github.com/baiwumm/Vue2-Admin/assets/41809797/32ce4ae4-204b-4fd5-9a47-1dfee930c63c)

### 访问pointA

访问`http://127.0.0.1:7001/pointA`可看到：

![image](https://github.com/baiwumm/Vue2-Admin/assets/41809797/ceb864bb-7286-4fe8-8907-836a2bbc347e)

终端显示如下：

![image](https://github.com/baiwumm/Vue2-Admin/assets/41809797/ae43fddf-c3f2-4759-bb03-009c0128ffe1)

### 访问pointB

访问`http://127.0.0.1:7001/pointB`可看到：

![image](https://github.com/baiwumm/Vue2-Admin/assets/41809797/477a2510-e32c-4ac8-ae35-7945e320b195)

终端显示如下：

![image](https://github.com/baiwumm/Vue2-Admin/assets/41809797/4fd073c0-6974-4c10-9985-f7e8a3c73248)

### 访问pointC

访问`http://127.0.0.1:7001/pointC`可看到：

![image](https://github.com/baiwumm/Vue2-Admin/assets/41809797/0ebf3c0d-263f-4244-a477-2fa47788e451)

终端显示如下：

![image](https://github.com/baiwumm/Vue2-Admin/assets/41809797/41073c2c-730d-4d02-b04e-76ec70853cab)


## 结论

说明在`get`请求对应的路由函数`index()`使用`ctx.session.index = "index"`形式设置值，在`post`请求对应的路由函数`pointB()`不能正常获取到值（`ctx.session.index`为`undefined`）。同时也说明在`post`请求对应的路由函数`pointB()`使用`ctx.session.pointB = "pointB"`形式设置值，在另一个`post`请求对应的路由函数`pointC()`也不能获取到值。

这是在 https://github.com/baiwumm/Vue2-Admin/issues/3#issue-2080155038 环境中测试的结果，由于对egg这个框架不是很了解，最终还是用了 https://github.com/baiwumm/Vue2-Admin/issues/3#issue-2080155038 提到的思路解决目前的问题，希望作者或者其他有缘人能提供更好的思路😊👏。
